# Site
name: "Tend Home Inc"
title: "Toronto"
description: "Snow Removal Service for Homes, Businesses or Places of Worship"
logo: 'assets/images/tendhome.jpg'
favicon: 'assets/images/tendhome.jpg'
include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, storage]
